# Generated by Django 2.1.2 on 2018-11-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181112_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
