# Generated by Django 2.1.2 on 2018-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='To',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='From',
            field=models.CharField(choices=[('clg', 'COLLEGE'), ('DNPT', 'DANAPUR'), ('PTNS', 'PATNA STATION'), ('ARPT', 'AIRPORT')], default='COLLEGE', max_length=10),
        ),
    ]
