# Generated by Django 2.1.2 on 2018-11-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181113_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='From',
            new_name='fromi',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='To',
            new_name='to',
        ),
    ]
