# Generated by Django 2.1.2 on 2018-11-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20181114_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='luser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
