# Generated by Django 2.1.2 on 2018-11-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20181114_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='luser',
        ),
    ]
