# Generated by Django 2.1.2 on 2018-11-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='fir',
        ),
    ]
