# Generated by Django 2.1.2 on 2018-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20181114_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fir',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fromi',
        ),
        migrations.RemoveField(
            model_name='post',
            name='to',
        ),
        migrations.AddField(
            model_name='post',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='route',
            field=models.CharField(choices=[('clg-dnp', 'COLLEGE-DANAPUR'), ('clg-ptnastn', 'COLLEGE-PATNA STATION'), ('clg-ptnaapt', 'COLLEGE-PATNA AIRPORT'), ('dnp-clg', 'DANAPUR-COLLEGE'), ('patnaapt-clg', 'PATNA AIRPORT-COLLEGE'), ('patnastn-clg', 'PATNA STATION-COLLEGE')], default='COLLEGE', max_length=10),
        ),
    ]
