# Generated by Django 2.1.2 on 2018-11-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20181114_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fir',
            field=models.CharField(default='', max_length=100),
        ),
    ]
