# Generated by Django 2.1.2 on 2018-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='route',
            field=models.CharField(choices=[('COLLEGE-DANAPUR', 'COLLEGE-DANAPUR'), ('COLLEGE-PATNA STATION', 'COLLEGE-PATNA STATION'), ('COLLEGE-PATNA AIRPOR', 'COLLEGE-PATNA AIRPORT'), ('DANAPUR-COLLEGE', 'DANAPUR-COLLEGE'), ('PATNA AIRPORT-COLLEGE', 'PATNA AIRPORT-COLLEGE'), ('PATNA STATION-COLLEGE', 'PATNA STATION-COLLEGE')], default='COLLEGE', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
